# Generated by Django 5.0.3 on 2024-05-14 15:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_orderitem_options_confirmemailtoken"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="confirmemailtoken",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="order",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="orderitem",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="parameter",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="productinfo",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="productparameter",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="shop",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
