# Регистрация пользователя
# Если явно не указываем тип пользователя, то он создаётся по-умолчанию с типом "buyer"
# То есть "покупатель"

POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
  "first_name": "qwertr",
  "last_name": "qwerty",
  "email": "qwertqe@mail.ru",
  "password": "qwer1234A",
  "position": "345345",
  "company": "qy-qyy",
  "contacts": "34-44",
  "username": "qaq"
}

###
# Потверждение email пользователя

 POST http://127.0.0.1:8000/api/v1/user/register/confirm
 Content-Type: application/json

 {
   "email": "qwertqe111@mail.ru",
   "token": "qwer1234Arwrgetregbegbg"
 }

###
# Авторизация пользователя

POST http://127.0.0.1:8000/api/v1/user/login
Content-Type: application/json

{
  "email": "qwertqe116@mail.ru",
  "password": "qwer1234A"
}

###