# Регистрация пользователя
# Если явно не указываем тип пользователя, то он создаётся по-умолчанию с типом "buyer"
# То есть "покупатель"

POST http://127.0.0.1:8000/api/v1/user/register
Content-Type: application/json

{
  "first_name": "qwertr",
  "last_name": "qwerty",
  "email": "qwertqe3@mail.ru",
  "password": "qwer1234A",
  "position": "345345",
  "company": "qy-qyy",
  "contacts": "34-44",
  "username": "qaq3",
  "type": "shop"
}

###
# Потверждение email пользователя

 POST http://127.0.0.1:8000/api/v1/user/register/confirm
Content-Type: application/json

 {
   "email": "qwertqe1@mail.ru",
   "token": "f0be670ccf6ea5aa10fd0a22dc6f0811"
 }

###
# Авторизация пользователя

POST http://127.0.0.1:8000/api/v1/user/login
Content-Type: application/json

{
  "email": "qwertqe1@mail.ru",
  "password": "qwer1234A"
}

###